{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "time-between-query.serviceAccountName" . }}
  labels:
{{ include "time-between-query.labels" . | nindent 4 }}
{{- end -}}
