name: kubernetes deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    container: alpine/helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p ~/.kube
      - run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - run: helm upgrade --install --namespace yoyota
          --set image.tag=${{ github.sha }}
          --history-max 2
          time-between-query ./helm
