name: "test"
on:
  - push
  - pull_request

jobs:
  test:
    services:
      influxdb:
        image: influxdb:alpine
        ports:
          - 8086:8086
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run test
